FROM ubuntu:18.04
MAINTAINER Matteo Di Giovinazzo <matteodg@gmail.com>

RUN wget https://download.netbeans.org/netbeans/8.1/final/bundles/netbeans-8.1-linux.sh -O /tmp/netbeans.sh -q && \
    chmod +x /tmp/netbeans.sh && \
    /tmp/netbeans.sh --silent
